version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  cliente-service:
    build: ./cliente-service
    container_name: cliente-service
    ports:
      - "8081:8080"
    depends_on:
      - kafka

  pedido-service:
    build: ./pedido-service
    container_name: pedido-service
    ports:
      - "8082:8080"
    depends_on:
      - kafka

  estoque-service:
    build: ./estoque-service
    container_name: estoque-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
